name: CI CD in Azure env

env: 
  AZURE_CONTAINER_REGISTRY: 'abbykuoacr1202.azurecr.io'
  
run-name: ${{ github.actor }} is testing out CICD on GitHub Actions 🚀
on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
      contents: read
  
jobs:
  Build-image:
    runs-on: ubuntu-latest
    steps:
      # Code checkout
      - name: Check out repository code
        uses: actions/checkout@v3
      
      # Set up Docker for ubuntu
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Login to ACR
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: 'abbykuoacr1202' 
          # Container registry password
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD}}
          # Container registry server url
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
   
      # Push docker image to ACR    
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: abbykuoacr1202.azurecr.io/hello-world-app:${{ github.sha }}
          file: ./Dockerfile
 
  Deploy-to-AKS:
    permissions:
      id-token: write
      contents: read
      actions: read
      
    runs-on: ubuntu-latest
    needs: [Build-image]
    environment: Production
    
    steps:
      # Code checkout
      - name: Check out repository code
        uses: actions/checkout@v3steps
      
      # Run Azure Login with OIDC to Azure
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # Azure Kubelogin
      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1
        with:
          # The version of kubelogin to use. Defaults to the latest version.
          kubelogin-version: 'latest'
        
      # Azure Kubernetes set context
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          # Resource Group Name
          resource-group: 'github_actions_rg'
          # AKS Cluster Name
          cluster-name: 'abbykuok8s1202'
          # AKS Cluster Subscription
          subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Get cluster admin credentials. Values: true or false
          admin: 'false'
          # Enables kubelogin for non-admin user scenario. Values: true or false
          use-kubelogin: 'true'
          
      # Substitute environment variables in a file
      - name: envsubst-action
        uses: danielr1996/envsubst-action@1.1.0
        env: 
          MONGODB_URI: ${{ secrets.MOGODI_URI }}
          CONTAINER_NAME: hello-world-app:${{ github.sha }}
          AZURE_CONTAINER_REGISTRY: ${{ env.AZURE_CONTAINER_REGISTRY }}
        with:
          # File to run substitutions on
          input: kubernetes/hello-world-deployment.yaml
          # File to write result to
          output: hello-world-deployment.yaml
      
      
      # Deploy to Kubernetes cluster 
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with: 
          action: deploy
          manifests: |
            hello-world-deployment.yaml
            kubernetes/hello-world-service.yaml
          images: |
            abbykuoacr1202.azurecr.io/hello-world-app:${{ github.sha }}
            
            
          
      
      
      
      
      
      
