name: CI CD in Azure env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
      contents: read
  
jobs:
  Build-image:
    runs-on: ubuntu-latest
    steps:
      # Code checkout
      - name: Check out repository code
        uses: actions/checkout@v3
      
      # Set up Docker for ubuntu
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Login to ACR
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: # default is 
          # Container registry password
          password: # default is 
          # Container registry server url
          login-server: # default is https://index.docker.io/v1/
   
      # Push docker image to ACR    
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/hello-world-app:${{ github.sha }}
          file: ./Dockerfile
 
  Deploy-to-AKS:
    permissions:
      id-token: write
      contents: read
      actions: read
      
    runs-on: ubuntu-latest
    needs: [Build-image]
    environment: Production
    
    steps:
      # Code checkout
      - name: Check out repository code
        uses: actions/checkout@v3steps:
      
      # Run Azure Login with OIDC to Azure
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # Azure Kubelogin
      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1
        with:
          # The version of kubelogin to use. Defaults to the latest version.
          kubelogin-version: 'latest'
        
      # Azure Kubernetes set context
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          # Resource Group Name
          resource-group: 
          # AKS Cluster Name
          cluster-name: 
          # AKS Cluster Subscription
          subscription: # optional
          # Get cluster admin credentials. Values: true or false
          admin: 'false'
          # Enables kubelogin for non-admin user scenario. Values: true or false
          use-kubelogin: 'true'
          
      # Substitue environment variables in a file
      - name: 
        uses: 
      
      
      # Deploy to Kubernetes cluster 
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with: 
          action: deploy
          manifests: |
            kubernetes/hello-world-deployment.yaml
            kubernetes/hello-world-service.yaml
          images: |
            user/hello-world-app:${{ github.sha }}
            
          
      
      
      
      
      
      
